# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Package
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Pack
        run: dotnet pack --no-restore
      - name: Add nuget.config
        run: dotnet nuget add source --username slogsdon7 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/slogsdon7/index.json"
      - uses: dotnet/nbgv@master
        id: nbgv
      - name: Push
        run: dotnet nuget push "artifacts/package/release/Spinitron.Client.${{ steps.nbgv.outputs.NuGetPackageVersion }}.nupkg"  --api-key ${{ secrets.GH_PAT }} --source "github"
      
